[project]
name = "fastmcp"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pandas",
    "numpy",
    "matplotlib",
    "pydantic",
    "scikit-learn",
    "httpx",
    "python-multipart",
    "boto3",
    "openai",
]

[tool.uv]
virtualenvs.in-project = true
